### ISSUE TITLE
Broken Link in the Configu Cloud Page

### ISSUE THREAD

**Issue by Smartmind12** [configu/docs#45]
The single source of truth should point to the Configuration as a code page however a broken link is present instead.

Kindly assign this issue to me so that i can update the link. 
![Screenshot 2023-10-08 at 5 17 51 PM](https://github.com/configu/docs/assets/91927689/878d901e-5807-44cb-abd3-d10fbd03c748)

**Comment by pelegpor** [comment]
Hello @Smartmind12 ,

Thank you for bringing this to our attention. To better address the issue, could you please provide more details? Specifically:

Which exact link is broken?
On which page did you encounter this issue?
The more information you can provide, the easier it will be for us to pinpoint and resolve the problem.

Of course, we'd greatly appreciate your help in fixing this. Once we have a clearer understanding of the issue, we'll be more than happy to assign it to you.

Thanks again for your commitment to improving the project!

Best regards,
Peleg

**Comment by Smartmind12** [comment]
> Hello @Smartmind12 ,
> 
> Thank you for bringing this to our attention. To better address the issue, could you please provide more details? Specifically:
> 
> Which exact link is broken? On which page did you encounter this issue? The more information you can provide, the easier it will be for us to pinpoint and resolve the problem.
> 
> Of course, we'd greatly appreciate your help in fixing this. Once we have a clearer understanding of the issue, we'll be more than happy to assign it to you.
> 
> Thanks again for your commitment to improving the project!
> 
> Best regards, Peleg

Hey @pelegpor I found the link broken in https://configu.com/docs/configu-cloud/ at the "source of truth" hyperlink.
![Screenshot 2023-10-08 at 8 02 19 PM](https://github.com/configu/docs/assets/91927689/44fc6baf-c476-4d6e-b72e-6b07f7f3460a)

**Comment by pelegpor** [comment]
Thanks for pointing that out, @Smartmind12. You're right, the link should indeed point to [https://configu.com/docs/configs-explorer](https://configu.com/docs/configs-explorer).

We'd be grateful if you could assist in rectifying this. Please feel free to open a PR addressing the issue. If you're unsure about the process, our Docs [contributing guide](https://github.com/configu/docs/blob/main/CONTRIBUTING.md) is a great place to start. Should you have any questions or need assistance, don't hesitate to ask here or join our Discord channel for more direct communication.

Thanks again for your keen observation and willingness to contribute!
