### ISSUE TITLE
Adding define of configuration source and provider

### ISSUE THREAD

**Issue by neelshah2409** [configu/docs#47]
![image](https://github.com/configu/docs/assets/71593494/f3dd4016-eef2-42a9-ad8c-3d8b5c85821c)
I would like to add definition of configuration source and provider here in the above list .

**Comment by ShatilKhan** [comment]
Hi please assign me the issue
I'd love to contribute to both these doc issues & will make my PRs ASAP

**Comment by pelegpor** [comment]
Hello @neelshah2409,

Thank you for taking the time to open this issue and contribute to our project. We truly value the insights and feedback from our community. Your involvement helps us improve and ensures that we're addressing the needs of our users.

We're looking forward to seeing your PR on this issue. 
Please feel free to continue sharing your thoughts and suggestions.

**Comment by Anurag-space** [comment]
@pelegpor 
i would like to contribute on this issue please assign me this issue

**Comment by neelshah2409** [comment]
Hey @pelegpor please review the PR

**Comment by RichardAkman** [comment]
We've been taking a close look at the new terminologies you've proposed, and we decided they don't quite align with our vision. We appreciate the suggestion!
